[package]
name = "koto-rc-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.koto]
version = "0.14.0"
default-features = false
features = ["rc"]
